services:
  - type: web
    name: distilbert-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3.10 python3.10-venv python3.10-dev
      python3.10 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install --prefer-binary -r requirements.txt
    startCommand: |
      . venv/bin/activate
      uvicorn distilbert_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14